import nodemailer from "nodemailer";
import { NextResponse } from "next/server";

// IMPORTANT SECURITY NOTE:
// In a real application, NEVER hardcode sensitive credentials like this.
// Always use environment variables (process.env.SMTP_USER, process.env.SMTP_PASS, etc.).

// --- HTML Email Templates (Refactored for Responsiveness and Aesthetics) ---

const getAdminEmailHtml = (name: string, email: string, message: string) => `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Bornosoft Inquiry</title>
    <style>
        /* Mobile responsive reset */
        @media only screen and (max-width: 600px) {
            .container { width: 100% !important; min-width: 100% !important; }
            .content-padding { padding: 20px !important; }
            .header-logo { width: 100px !important; }
        }
    </style>
</head>
<body style="margin: 0; padding: 0; background-color: #f3f4f6; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';">
    <center style="width: 100%; table-layout: fixed; background-color: #f3f4f6; padding: 30px 0;">
        <table align="center" class="container" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; max-width: 600px; background-color: white; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.05);">
            <!-- Header Section -->
            <tr>
                <td align="center" style="background-color: #4f46e5; color: white; padding: 30px; border-top-left-radius: 8px; border-top-right-radius: 8px;">
                    <img src="https://i.ibb.co/mCsz8HRX/Chat-GPT-Image-Oct-19-2025-08-42-00-PM.png" alt="Bornosoft Logo" class="header-logo" style="width: 120px; height: auto; display: block; margin-bottom: 15px;">
                    <h1 style="margin: 0; font-size: 24px; font-weight: 700;">New Client Inquiry 🚀</h1>
                </td>
            </tr>

            <!-- Content Section -->
            <tr>
                <td class="content-padding" style="padding: 40px 30px;">
                    <p style="font-size: 16px; line-height: 1.6; color: #1f2937;">Hello <strong>Bornosoft Team</strong>,</p>
                    <p style="font-size: 16px; line-height: 1.6; color: #1f2937;">A new message has been submitted through your website contact form. Please review the details below and follow up promptly.</p>
                    
                    <!-- Client Details Table -->
                    <table style="width: 100%; margin: 25px 0; border-collapse: collapse; border: 1px solid #e5e7eb; border-radius: 6px; overflow: hidden;">
                        <tr style="background-color: #f9fafb;">
                            <td style="padding: 12px 15px; font-weight: 600; width: 30%; color: #374151; border-right: 1px solid #e5e7eb;">👤 Name:</td>
                            <td style="padding: 12px 15px; width: 70%; color: #4b5563;">${name}</td>
                        </tr>
                        <tr>
                            <td style="padding: 12px 15px; font-weight: 600; width: 30%; color: #374151; border-right: 1px solid #e5e7eb; border-top: 1px solid #e5e7eb;">📧 Email:</td>
                            <td style="padding: 12px 15px; width: 70%; color: #4b5563; border-top: 1px solid #e5e7eb;"><a href="mailto:${email}" style="color: #4f46e5; text-decoration: none;">${email}</a></td>
                        </tr>
                    </table>

                    <p style="font-size: 16px; font-weight: 600; color: #1f2937; margin-bottom: 10px;">💬 Message:</p>
                    <div style="background: #f0f3ff; border: 1px solid #d1d5db; padding: 20px; border-radius: 8px; color: #1f2937; line-height: 1.7;">
                        ${message.replace(/\n/g, "<br>")}
                    </div>
                </td>
            </tr>

            <!-- Footer Section -->
            <tr>
                <td align="center" style="background-color: #f9fafb; padding: 20px 30px; border-bottom-left-radius: 8px; border-bottom-right-radius: 8px; font-size: 13px; color: #6b7280; border-top: 1px solid #e5e7eb;">
                    <p style="margin: 0;">This email was automatically generated by the Bornosoft contact form.</p>
                    <p style="margin-top: 5px;">© ${new Date().getFullYear()} Bornosoft NR. All rights reserved.</p>
                </td>
            </tr>
        </table>
    </center>
</body>
</html>
`;

const getClientConfirmationHtml = (name: string, message: string) => `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bornosoft Confirmation</title>
    <style>
        /* Mobile responsive reset */
        @media only screen and (max-width: 600px) {
            .container { width: 100% !important; min-width: 100% !important; }
            .content-padding { padding: 20px !important; }
            .header-logo { width: 100px !important; }
        }
    </style>
</head>
<body style="margin: 0; padding: 0; background-color: #f3f4f6; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';">
    <center style="width: 100%; table-layout: fixed; background-color: #f3f4f6; padding: 30px 0;">
        <table align="center" class="container" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; max-width: 600px; background-color: white; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.05);">
            <!-- Header Section -->
            <tr>
                <td align="center" style="background-color: #4f46e5; color: white; padding: 30px; border-top-left-radius: 8px; border-top-right-radius: 8px;">
                    <!-- Using the same absolute URL for the logo -->
                    <img src="https://i.ibb.co/mCsz8HRX/Chat-GPT-Image-Oct-19-2025-08-42-00-PM.png" alt="Bornosoft Logo" class="header-logo" style="width: 120px; height: auto; display: block; margin-bottom: 15px;">
                    <h1 style="margin: 0; font-size: 24px; font-weight: 700;">🤝 Your Inquiry is Received!</h1>
                </td>
            </tr>

            <!-- Content Section -->
            <tr>
                <td class="content-padding" style="padding: 40px 30px;">
                    <p style="font-size: 16px; line-height: 1.6; color: #1f2937;">Hi <strong>${name}</strong>,</p>
                    <p style="font-size: 16px; line-height: 1.6; color: #1f2937;">Thank you for reaching out to <strong>Bornosoft NR</strong>! We've successfully received your message and appreciate you taking the time to contact us.</p>
                    <p style="font-size: 16px; line-height: 1.6; color: #1f2937;">Our team will review your inquiry and aim to get back to you within 24-48 business hours.</p>

                    <p style="font-size: 16px; font-weight: 600; color: #1f2937; margin-top: 25px; margin-bottom: 10px;">📝 Your Message Summary:</p>
                    <div style="background: #f9fafb; border: 1px solid #e5e7eb; padding: 20px; border-left: 4px solid #4f46e5; border-radius: 8px; color: #374151; line-height: 1.7;">
                        ${message.replace(/\n/g, "<br>")}
                    </div>
                    
                    <p style="margin-top: 30px; font-size: 16px; color: #1f2937;">
                        Best regards,<br>
                        <strong>The Bornosoft Team</strong><br>
                        <a href="https://bornosoftnr.com" style="color:#4f46e5; text-decoration:none; font-weight: 600;">www.bornosoftnr.com</a>
                    </p>
                </td>
            </tr>

            <!-- Footer Section -->
            <tr>
                <td align="center" style="background-color: #f9fafb; padding: 20px 30px; border-bottom-left-radius: 8px; border-bottom-right-radius: 8px; font-size: 13px; color: #6b7280; border-top: 1px solid #e5e7eb;">
                    <p style="margin: 0;">If you have any urgent questions, please call us.</p>
                    <p style="margin-top: 5px;">© ${new Date().getFullYear()} Bornosoft NR. All rights reserved.</p>
                </td>
            </tr>
        </table>
    </center>
</body>
</html>
`;

// --- API Route Handler ---

export async function POST(req: Request) {
  try {
    const { name, email, message } = await req.json();

    // 1. Validate Input (Basic Check)
    if (!name || !email || !message) {
      return NextResponse.json(
        {
          success: false,
          message:
            "❌ Please fill out all required fields (Name, Email, Message).",
        },
        { status: 400 }
      );
    }

    // 2. Setup Transporter
    const transporter = nodemailer.createTransport({
      host: "mail.bornosoftnr.com",
      port: 465,
      secure: true,
      auth: {
        user: "info@bornosoftnr.com",
        pass: "2FZY{jx24)T$KzLm", // Replace with secure environment variable
      },
    });

    // 3. Generate HTML Content
    const adminHtml = getAdminEmailHtml(name, email, message);
    const clientHtml = getClientConfirmationHtml(name, message);

    // 4. Send Emails Concurrently
    await Promise.all([
      // A. Email to Bornosoft Team (Admin)
      transporter.sendMail({
        from: `"${name} (Web Inquiry)" <info@bornosoftnr.com>`, // Display client's name
        replyTo: email, // Reply goes back to the client
        to: "info@bornosoftnr.com",
        subject: `[New Inquiry] Contact Form Submission from ${name}`,
        html: adminHtml,
      }),

      // B. Email to Client (Confirmation)
      transporter.sendMail({
        from: '"Bornosoft NR Team" <no-reply@bornosoftnr.com>',
        replyTo: "info@bornosoftnr.com", // Client replies to the main info mailbox
        to: email,
        subject: `Confirmation: We've Received Your Message - Bornosoft NR`,
        html: clientHtml,
      }),
    ]);

    // 5. Success Response
    return NextResponse.json({
      success: true,
      message:
        "✅ Your message was sent successfully. A confirmation email has been sent to your inbox.",
    });
  } catch (error) {
    // 6. Error Handling
    console.error("Email sending error:", error);
    return NextResponse.json(
      {
        success: false,
        message:
          "❌ Failed to send email due to a server error. Please check the console.",
      },
      { status: 500 }
    );
  }
}
